sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - poppler-utils

before_install:
  - docker build -t elfolink/alpine-java-wkhtmltopdf .

script:
  - docker run --rm elfolink/alpine-java-wkhtmltopdf wkhtmltopdf -q google.com - - > test.pdf 
  - pdftotext -layout test.pdf - | grep -q Google

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag elfolink/alpine-java-wkhtmltopdf elfolink/alpine-java-wkhtmltopdf:$TRAVIS_BUILD_NUMBER;
    docker push elfolink/alpine-java-wkhtmltopdf;
    docker push elfolink/alpine-java-wkhtmltopdf:$TRAVIS_BUILD_NUMBER;
    fi
